### ISSUE TITLE
Possible to get Air quality and temperature

### ISSUE THREAD

**Issue by tvillingett** [amida-tech/withings-lib#12]
Can you get this from a withings scale, I cannot find how?

**Comment by jsachs** [comment]
@tvillingett the Withings developer API does not currently support these measures. It only support activity measures, body measures and sleep measures. Unfortunately their API is not very well supported, and I don't see this changing anytime soon.

From the [Withings API FAQ](http://oauth.withings.com/api/faq): "Air quality and temperature data from the Smart Body Analyzer are currently not supported."
